/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../app/src/sanity/schema.json
export type Highlight = {
  badge?: string;
  title?: string;
  body?: string;
  cta?: Cta;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ObjectImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  _type: "image";
};

export type ItemsObjectImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "items.object.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type CtaBand = {
  _type: "ctaBand";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  eyebrow: string;
  title: string;
  body: string;
  primaryCta?: Cta;
  secondaryCta?: Cta;
};

export type CrossLinks = {
  _type: "crossLinks";
  items: Array<{
    title: string;
    body: string;
    link: Link;
    _key: string;
  }>;
};

export type FaqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faq";
};

export type Faqs = {
  _type: "faqs";
  eyebrow: string;
  title: string;
  intro: string;
  link?: Cta;
  faqs: Array<
    {
      _key: string;
    } & FaqReference
  >;
};

export type Steps = {
  _type: "steps";
  eyebrow: string;
  title: string;
  lead: string;
  cta?: Cta;
  items: Array<{
    number: string;
    title: string;
    body: string;
    image: ItemsObjectImage;
    _key: string;
  }>;
};

export type Benefits = {
  _type: "benefits";
  eyebrow: string;
  title: string;
  lead: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  items: Array<{
    icon:
      "person" | "camera" | "chart" | "doc" | "house" | "renovate" | "scale";
    title: string;
    body: string;
    _key: string;
  }>;
};

export type PageHero = {
  _type: "pageHero";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  breadcrumbLabel?: string;
  eyebrow: string;
  title: string;
  titleHighlight?: string;
  lead: string;
  primaryCta?: Cta;
  secondaryCta?: Cta;
};

export type MediaText = {
  _type: "mediaText";
  eyebrow: string;
  title: string;
  paragraphs: Array<string>;
  cta?: Cta;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type Services = {
  _type: "services";
  title: string;
  lead: string;
  items: Array<{
    label: string;
    title: string;
    description: string;
    image: ObjectImage;
    link: Link;
    _key: string;
  }>;
  highlight?: Highlight;
};

export type Intro = {
  _type: "intro";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  stampValue: string;
  stampLabel: string;
  eyebrow: string;
  title: string;
  titleHighlight?: string;
  leads: Array<string>;
  facts?: Array<{
    value: string;
    label: string;
    _key: string;
  }>;
  link?: Cta;
};

export type Hero = {
  _type: "hero";
  slides: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  eyebrow: string;
  title: string;
  titleHighlight?: string;
  lead: string;
  primaryCta: Cta;
  secondaryCta: Cta;
  badgeLabel: string;
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & Hero)
  | ({
      _key: string;
    } & PageHero)
  | ({
      _key: string;
    } & Intro)
  | ({
      _key: string;
    } & Services)
  | ({
      _key: string;
    } & MediaText)
  | ({
      _key: string;
    } & Benefits)
  | ({
      _key: string;
    } & Steps)
  | ({
      _key: string;
    } & Faqs)
  | ({
      _key: string;
    } & CrossLinks)
  | ({
      _key: string;
    } & CtaBand)
>;

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Cta = {
  _type: "cta";
  label: string;
  linkType: "internal" | "external";
  internalLink?: PageReference;
  href?: string;
};

export type Link = {
  _type: "link";
  linkType: "internal" | "external";
  internalLink?: PageReference;
  href?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  linkGroups?: Array<{
    title: string;
    links?: Array<{
      label: string;
      linkType: "internal" | "external";
      internalLink?: PageReference;
      href?: string;
      _type: "footerLink";
      _key: string;
    }>;
    _type: "linkGroup";
    _key: string;
  }>;
  socialLinks?: Array<{
    platform: string;
    url: string;
    _type: "socialLink";
    _key: string;
  }>;
  copyright?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navLeft?: Array<{
    label: string;
    linkType: "internal" | "external";
    internalLink?: PageReference;
    href?: string;
    _type: "navLink";
    _key: string;
  }>;
  navRight?: Array<{
    label: string;
    linkType: "internal" | "external";
    internalLink?: PageReference;
    href?: string;
    _type: "navLink";
    _key: string;
  }>;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  answer: string;
  link?: Cta;
  afterLink?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  seo?: Seo;
  content?: PageBuilder;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Highlight
  | SanityImageAssetReference
  | ObjectImage
  | ItemsObjectImage
  | CtaBand
  | CrossLinks
  | FaqReference
  | Faqs
  | Steps
  | Benefits
  | PageHero
  | MediaText
  | Services
  | Intro
  | Hero
  | PageBuilder
  | PageReference
  | Cta
  | Link
  | Seo
  | Footer
  | Navigation
  | Faq
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../app/src/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    slug,    seo,    content[]{      ...,      primaryCta{  ...,  internalLink->{    "slug": slug.current  }},      secondaryCta{  ...,  internalLink->{    "slug": slug.current  }},      link{  ...,  internalLink->{    "slug": slug.current  }},      cta{  ...,  internalLink->{    "slug": slug.current  }},      highlight{        ...,        cta{  ...,  internalLink->{    "slug": slug.current  }}      },      items[]{        ...,        link{  ...,  internalLink->{    "slug": slug.current  }},        cta{  ...,  internalLink->{    "slug": slug.current  }}      },      _type == "faqs" => {        ...,        faqs[]->{          ...,          link{  ...,  internalLink->{    "slug": slug.current  }}        },        link{  ...,  internalLink->{    "slug": slug.current  }}      }    }  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  seo: Seo | null;
  content: Array<
    | {
        _key: string;
        _type: "benefits";
        eyebrow: string;
        title: string;
        lead: string;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        items: Array<{
          icon:
            | "camera"
            | "chart"
            | "doc"
            | "house"
            | "person"
            | "renovate"
            | "scale";
          title: string;
          body: string;
          _key: string;
          link: null;
          cta: null;
        }>;
        primaryCta: null;
        secondaryCta: null;
        link: null;
        cta: null;
        highlight: null;
      }
    | {
        _key: string;
        _type: "crossLinks";
        items: Array<{
          title: string;
          body: string;
          link: {
            _type: "link";
            linkType: "external" | "internal";
            internalLink: {
              slug: string;
            } | null;
            href?: string;
          };
          _key: string;
          cta: null;
        }>;
        primaryCta: null;
        secondaryCta: null;
        link: null;
        cta: null;
        highlight: null;
      }
    | {
        _key: string;
        _type: "ctaBand";
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        eyebrow: string;
        title: string;
        body: string;
        primaryCta: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        secondaryCta: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        link: null;
        cta: null;
        highlight: null;
        items: null;
      }
    | {
        _key: string;
        _type: "faqs";
        eyebrow: string;
        title: string;
        intro: string;
        link: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        faqs: Array<{
          _id: string;
          _type: "faq";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title: string;
          answer: string;
          link: {
            _type: "cta";
            label: string;
            linkType: "external" | "internal";
            internalLink: {
              slug: string;
            } | null;
            href?: string;
          } | null;
          afterLink?: string;
        }>;
        primaryCta: null;
        secondaryCta: null;
        cta: null;
        highlight: null;
        items: null;
      }
    | {
        _key: string;
        _type: "hero";
        slides: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
          _key: string;
        }>;
        eyebrow: string;
        title: string;
        titleHighlight?: string;
        lead: string;
        primaryCta: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        };
        secondaryCta: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        };
        badgeLabel: string;
        link: null;
        cta: null;
        highlight: null;
        items: null;
      }
    | {
        _key: string;
        _type: "intro";
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        stampValue: string;
        stampLabel: string;
        eyebrow: string;
        title: string;
        titleHighlight?: string;
        leads: Array<string>;
        facts?: Array<{
          value: string;
          label: string;
          _key: string;
        }>;
        link: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        primaryCta: null;
        secondaryCta: null;
        cta: null;
        highlight: null;
        items: null;
      }
    | {
        _key: string;
        _type: "mediaText";
        eyebrow: string;
        title: string;
        paragraphs: Array<string>;
        cta: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        primaryCta: null;
        secondaryCta: null;
        link: null;
        highlight: null;
        items: null;
      }
    | {
        _key: string;
        _type: "pageHero";
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
        };
        breadcrumbLabel?: string;
        eyebrow: string;
        title: string;
        titleHighlight?: string;
        lead: string;
        primaryCta: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        secondaryCta: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        link: null;
        cta: null;
        highlight: null;
        items: null;
      }
    | {
        _key: string;
        _type: "services";
        title: string;
        lead: string;
        items: Array<{
          label: string;
          title: string;
          description: string;
          image: ObjectImage;
          link: {
            _type: "link";
            linkType: "external" | "internal";
            internalLink: {
              slug: string;
            } | null;
            href?: string;
          };
          _key: string;
          cta: null;
        }>;
        highlight: {
          badge?: string;
          title?: string;
          body?: string;
          cta: {
            _type: "cta";
            label: string;
            linkType: "external" | "internal";
            internalLink: {
              slug: string;
            } | null;
            href?: string;
          } | null;
        } | null;
        primaryCta: null;
        secondaryCta: null;
        link: null;
        cta: null;
      }
    | {
        _key: string;
        _type: "steps";
        eyebrow: string;
        title: string;
        lead: string;
        cta: {
          _type: "cta";
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
        } | null;
        items: Array<{
          number: string;
          title: string;
          body: string;
          image: ItemsObjectImage;
          _key: string;
          link: null;
          cta: null;
        }>;
        primaryCta: null;
        secondaryCta: null;
        link: null;
        highlight: null;
      }
  > | null;
} | null;

// Source: ../app/src/sanity/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{    "slug": slug.current,    _updatedAt  }
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: ../app/src/sanity/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_id == "navigation"][0]{    navLeft[]{  ...,  internalLink->{    "slug": slug.current  }},    navRight[]{  ...,  internalLink->{    "slug": slug.current  }}  }
export type NAVIGATION_QUERY_RESULT =
  | {
      navLeft: null;
      navRight: null;
    }
  | {
      navLeft: Array<{
        label: string;
        linkType: "external" | "internal";
        internalLink: {
          slug: string;
        } | null;
        href?: string;
        _type: "navLink";
        _key: string;
      }> | null;
      navRight: Array<{
        label: string;
        linkType: "external" | "internal";
        internalLink: {
          slug: string;
        } | null;
        href?: string;
        _type: "navLink";
        _key: string;
      }> | null;
    }
  | null;

// Source: ../app/src/sanity/queries.ts
// Variable: FOOTER_QUERY
// Query: *[_id == "footer"][0]{    linkGroups[]{      title,      links[]{  ...,  internalLink->{    "slug": slug.current  }}    },    copyright  }
export type FOOTER_QUERY_RESULT =
  | {
      linkGroups: null;
      copyright: null;
    }
  | {
      linkGroups: Array<{
        title: string;
        links: Array<{
          label: string;
          linkType: "external" | "internal";
          internalLink: {
            slug: string;
          } | null;
          href?: string;
          _type: "footerLink";
          _key: string;
        }> | null;
      }> | null;
      copyright: string | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    seo,\n    content[]{\n      ...,\n      primaryCta{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n},\n      secondaryCta{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n},\n      link{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n},\n      cta{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n},\n      highlight{\n        ...,\n        cta{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n}\n      },\n      items[]{\n        ...,\n        link{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n},\n        cta{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n}\n      },\n      _type == "faqs" => {\n        ...,\n        faqs[]->{\n          ...,\n          link{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n}\n        },\n        link{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n}\n      }\n    }\n  }\n': PAGE_QUERY_RESULT;
    '\n  *[_type == "page" && defined(slug.current)]{\n    "slug": slug.current,\n    _updatedAt\n  }\n': PAGE_SLUGS_QUERY_RESULT;
    '\n  *[_id == "navigation"][0]{\n    navLeft[]{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n},\n    navRight[]{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n}\n  }\n': NAVIGATION_QUERY_RESULT;
    '\n  *[_id == "footer"][0]{\n    linkGroups[]{\n      title,\n      links[]{\n  ...,\n  internalLink->{\n    "slug": slug.current\n  }\n}\n    },\n    copyright\n  }\n': FOOTER_QUERY_RESULT;
  }
}
